/**
 *  Link property paths that should be generated by schema
 */

const linkPaths: { [k: string]: { [k: string]: string[] } } = {
  'blog': {
    'organization': [
      'blog',
      'organization'
    ]
  },
  'post': {
    'blog': [
      'post',
      'blog'
    ],
    'organization': [
      'post',
      'blog',
      'organization'
    ]
  },
  'team': {
    'organization': [
      'team',
      'organization'
    ]
  },
  'user': {
    'organization': [
      'user',
      'organization'
    ]
  }
};

export default linkPaths;
