/**
 *  Link property paths that should be generated by schema
 */
export default {
  'Blog': {
    'Organization': [
      'Blog',
      'Organization'
    ]
  },
  'Post': {
    'Blog': [
      'Post',
      'Blog'
    ]
  },
  'Team': {
    'Organization': [
      'Team',
      'Organization'
    ]
  },
  'User': {
    'Organization': [
      'User',
      'Team',
      'Organization'
    ]
  }
};
