/**
 *  Link property paths that should be generated by schema
 */

const linkPaths: { [k: string]: { [k: string]: string[] } } = {
  'Blog': {
    'Organization': [
      'Blog',
      'Organization'
    ]
  },
  'Post': {
    'Blog': [
      'Post',
      'Blog'
    ]
  },
  'Team': {
    'Organization': [
      'Team',
      'Organization'
    ]
  },
  'User': {
    'Organization': [
      'User',
      'Team',
      'Organization'
    ]
  }
};

export default linkPaths;
